@startuml

class World
class Grid {
    List<Cell> getCells(List<Coordinates> coordinates)
}
class Cell
class Coordinates {
    x
    y
    List<Coordinates> getNeighbours()
}
enum CellState {
    ALIVE
    DEAD
}

World -- Grid
Grid -- Cell
Cell -- Coordinates
Cell -- CellState

@enduml